export * from './advance-features.component';
export * from './basic-features.component';
export * from './hero.component';
export * from './how-it-work.component';
export * from './plaform-milstones.component';
export * from './contact-us.component';
export * from './pricing-section.component';
export * from './support-feature.component';
export * from './type-writer.component';
